DELETE  http://localhost:8000/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNjaGFkcmFuQGdtYWlsLmNvbSIsImV4cCI6MTcyNDkxNTA2MiwidXNlcklkIjoxfQ.nCnabjuIMUmwFnwPcc3RPvyrYxWYWXBmR3HxKZQpa2s